sudo: false
language: ruby
cache: bundler
before_install:
  # Since Rails 4.2 only supports rubygems < 2, we must install an older version for it.
  - >
    if [[ "$BUNDLE_GEMFILE" =~ "rails42" ]]; then
      rvm @global do gem install rubygems-update -v '<2'
      update_rubygems
      rvm @global do gem uninstall bundler --force --executables
      rvm @global do gem install bundler -v "~> 1.3"
    fi

notifications:
  webhooks:
    # With COVERALLS_PARALLEL, coverage information sent to coveralls will not be processed until
    # this webhook is sent.
    # https://coveralls.zendesk.com/hc/en-us/articles/203484329-Parallel-Build-Webhook
    - secure: "YnHYbTq51ySistjvOxsuNhyg4GLuUffEJstTYeGYXiBF7HG5h43IVYo8KNuLzwkgsOYBcNo+YMdQX7qCqJffSbhsr1FZRSzBmjFFxcyD4hu+ukM2theZ4mePVAZiePscYvQPRNY4hIb4d3egStJEytkalDhB3sOebF57tIaCssg="
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails42_haml.gemfile
  - gemfiles/rails50_haml.gemfile
  - gemfiles/rails51_haml.gemfile
  - gemfiles/rails52_haml.gemfile
  - gemfiles/rails42_boc.gemfile
  - gemfiles/rails50_boc.gemfile
  - gemfiles/rails51_boc.gemfile
  - gemfiles/rails52_boc.gemfile
  - gemfiles/rack.gemfile
  - gemfiles/rack_boc.gemfile
  - gemfiles/pry09.gemfile
  - gemfiles/pry010.gemfile
  - gemfiles/pry011.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/pry010.gemfile
    - gemfile: gemfiles/pry011.gemfile
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails42_boc.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails42_haml.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails42_boc.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails42_haml.gemfile
